### ISSUE TITLE
S3Auth error

### ISSUE THREAD

**Issue by Tux-Panik** [brianwarehime/inSp3ctor#2]
Dear,

Thanks for this useful tool.
I just had an error running the script.
Before, as prerequisite, I installed "awsauth", using:
`sudo pip install awsauth`

Then, I ran the script but it raised the following exception:
`ImportError: cannot import name S3Auth`

So, I changed the first import as below and it solves the issue:
`import awsauth`

Sure, I probably missed something... but what is it?

Thanks,
Regards,
Julien

**Comment by KhasMek** [comment]
Would you pull the lastest code and test again and follow up/close, please? https://github.com/brianwarehime/inSp3ctor/commit/78b01dbb0c6163144bdcf14dc9a6eedd81b8b88b should have fixed your issue it.

**Comment by Tux-Panik** [comment]
Thanks for the change. It works fine now ;-)
